CREATE DATABASE HeroVired;


CREATE TABLE STUDENT(
STUDENT_ID INT NOT NULL,
STUDENT_NAME VARCHAR(30) NOT NULL,
STUDENT_MARKS INT NOT NULL
);


INSERT INTO STUDENT VALUES
(2000,"Bma",90),
(2001,"linga",67),
(2002,"sai",63),
(2003,"kummara",98),
(2004,"Mohit",54),
(2005,"Bhavesh",97),
(2006,"Dinesh",23),
(2007,"Nithin",67);

SELECT * FROM STUDENT WHERE STUDENT_MARKS = 90;

SELECT * FROM STUDENT WHERE STUDENT_MARKS >= 64;

SELECT * FROM STUDENT WHERE STUDENT_MARKS > 67;

SELECT * FROM STUDENT WHERE STUDENT_MARKS != 67;

SELECT * FROM STUDENT WHERE STUDENT_MARKS <> 90;

-- IS EQUALS TO --->  ( "    =    " )
SELECT * FROM STUDENT WHERE STUDENT_MARKS = 67;

-- BETWEEN Keyword.
SELECT * FROM STUDENT WHERE STUDENT_MARKS BETWEEN 61 AND 70;

-- ASC Keyword Usage
SELECT * FROM STUDENT 
WHERE STUDENT_MARKS BETWEEN 61 AND 90 ORDER BY STUDENT_MARKS ASC;

-- DESC Keyword Usage
SELECT * FROM STUDENT
WHERE STUDENT_MARKS BETWEEN 61 AND 67 ORDER BY STUDENT_MARKS DESC;

SELECT COUNT(DISTINCT STUDENT_MARKS) FROM STUDENT;

SELECT * FROM STUDENT
WHERE NOT STUDENT_MARKS = 67 AND
NOT STUDENT_MARKS = 64;

SELECT * FROM STUDENT WHERE NOT STUDENT_MARKS BETWEEN 60 AND 70;

SELECT * FROM STUDENT LIMIT 3;

-- SELECT * FROM STUDENT WHERE STUDENT_NAME = "B%";




SELECT * FROM STUDENT;










CREATE TABLE DOB(
DATE_ DATE NOT NULL
);

INSERT INTO DOB VALUES ("2020-05-21");

SELECT * FROM DOB;